"""README's per-scenario table is generated, and may not drift from the tree (T5.3, T5.6).

The execution plan's T5.3 asks for *"the 10-scenario eval table up top"*. README had per-class
tables two hundred lines down and no per-scenario table anywhere. `evalharness.scenario_table`
builds one from `evals/runs/`; README embeds it between two markers; this file fails the moment
the two disagree - the same discipline as `test_results_staleness`, because a table that is
regenerated by hand is a table that is regenerated until the first time it is not.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from evalharness import scenario_table as st

REPO_ROOT = Path(__file__).resolve().parents[1]
README = REPO_ROOT / "README.md"


def test_readme_carries_exactly_what_the_tree_generates() -> None:
    """Byte for byte, markers included. `uv run python -m evalharness.scenario_table --write` is
    the fix, and reading the diff it produces is the review."""
    stamp = st.current_stamp()
    expected = st.render(stamp, st.rows(stamp))

    assert st.embedded(README) == expected, (
        "README.md's scenario table does not match evals/runs/ at the current stamp. "
        "Regenerate: uv run python -m evalharness.scenario_table --write"
    )


def test_the_table_sits_up_top_before_the_prerequisites() -> None:
    """*"Up top"* is the requirement; a correct table under the roadmap would not meet it."""
    text = README.read_text()

    assert text.index(st.BEGIN) < text.index("## Prerequisites")


def test_the_headline_prose_matches_the_table_it_summarises() -> None:
    """The three figures in the sentence above the table are written by hand and would go stale
    exactly as the RESULTS banner did. They are read back here against the same totals."""
    stamp = st.current_stamp()
    total = st.Tally()
    rows = st.rows(stamp)
    for row in rows:
        total = total + row.at_stamp
    text = README.read_text()
    glance = text[text.index("## Results at a glance") : text.index(st.BEGIN)]
    after = text[text.index(st.END) : text.index("## Prerequisites")]

    service = re.search(r"Culprit service (\d+) / (\d+)", glance)
    fault = re.search(r"fault class (\d+) / (\d+)", glance)
    assert service and fault, "the headline sentence names both figures"
    assert tuple(map(int, service.groups())) == (total.service_correct, total.service_answered)
    assert tuple(map(int, fault.groups())) == (total.class_correct, total.class_answered)

    abstained = re.search(r"(\d+) of (\d+) runs at this stamp named no class", after)
    assert abstained and tuple(map(int, abstained.groups())) == (total.abstained, total.n)

    unrun = re.search(r"(\d+) of the (\d+) dev scenarios and\s+all (\d+) holdout scenarios", after)
    assert unrun, "the sentence about what has not been run is still there"
    dev = [r for r in rows if r.split == "dev"]
    holdout = [r for r in rows if r.split == "holdout"]
    assert tuple(map(int, unrun.groups())) == (
        sum(1 for r in dev if r.at_stamp.n == 0),
        len(dev),
        len(holdout),
    )
    assert all(r.at_stamp.n == 0 for r in holdout), "the sentence says *all* holdout"
    assert re.search(r"Every one of the (\d+) has been scored", after).group(1) == str(len(rows))


# --- what is and is not counted ---------------------------------------------------------------


def _manifest(
    scenario: str,
    stamp: str = "b6837dd449ca",
    *,
    demo: bool = False,
    baseline: bool = False,
    world: str = st.CURRENT_WORLD,
    abstained: bool = False,
    correct: bool = True,
    service: bool | None = True,
    discarded: bool = False,
) -> dict:
    m: dict = {
        "run_id": f"20260907T000000Z-{scenario}",
        "scenario_id": scenario,
        "injected_at": "2026-09-07T00:00:00+00:00",
        "demo": demo,
        "freeze": {"world": {"compose_digest": world + "0" * 52, "host_platform": "Darwin/arm64"}},
    }
    if baseline:
        m["baseline"] = "b0"
    if discarded:
        m["discarded"] = {"reason": "no-alert"}
        return m
    m["score"] = {
        "runtime_version": f"faultline/0.0.1+prompts:{stamp}",
        "fault_class": {"abstained": abstained, "correct": correct and not abstained},
    }
    if service is not None:
        m["score"]["service"] = {"abstained": False, "correct": service}
    return m


def _tree(tmp_path: Path, manifests: list[dict]) -> Path:
    runs = tmp_path / "runs"
    for i, m in enumerate(manifests):
        d = runs / f"{i:03d}-{m['scenario_id']}"
        d.mkdir(parents=True)
        (d / "manifest.json").write_text(json.dumps(m))
    return runs


def test_demos_baselines_discards_and_other_worlds_are_not_samples(tmp_path: Path) -> None:
    """Each exclusion is one the repository argued for elsewhere: `counts_toward_aggregates` for
    demos, RESULTS.md's own column for the B0 arm, ADR-0022 §3.3 for discards, and
    `group_by_generation` for worlds. The table inherits all four rather than re-deciding."""
    scenario = "cart-redis-misconfig"
    runs = _tree(
        tmp_path,
        [
            _manifest(scenario),
            _manifest(scenario, demo=True),
            _manifest(scenario, baseline=True),
            _manifest(scenario, discarded=True),
            _manifest(scenario, world="4a7690c6fdda"),
            _manifest(scenario, stamp="000000000000"),
        ],
    )

    row = next(r for r in st.rows("b6837dd449ca", runs=runs) if r.scenario_id == scenario)

    assert row.at_stamp.n == 1
    assert row.on_world.n == 2, "the other stamp counts on the world, the other world does not"


def test_an_abstention_is_neither_correct_nor_wrong(tmp_path: Path) -> None:
    scenario = "ad-memory-squeeze"
    runs = _tree(
        tmp_path,
        [
            _manifest(scenario, correct=True),
            _manifest(scenario, correct=False),
            _manifest(scenario, abstained=True),
        ],
    )

    tally = next(r for r in st.rows("b6837dd449ca", runs=runs) if r.scenario_id == scenario)

    assert (tally.at_stamp.class_correct, tally.at_stamp.class_answered) == (1, 2)
    assert tally.at_stamp.abstained == 1
    assert st._cell(1, 2) == "1 / 2" and st._cell(0, 0) == "—"


def test_a_run_without_a_service_score_leaves_that_column_alone(tmp_path: Path) -> None:
    """Service was scored from T4.2; an older run is not a miss on an axis it was never asked."""
    scenario = "shipping-wrong-image"
    runs = _tree(tmp_path, [_manifest(scenario, service=None), _manifest(scenario, service=True)])

    tally = next(r for r in st.rows("b6837dd449ca", runs=runs) if r.scenario_id == scenario)

    assert tally.at_stamp.n == 2
    assert (tally.at_stamp.service_correct, tally.at_stamp.service_answered) == (1, 1)


def test_every_unblocked_scenario_is_a_row_and_no_blocked_or_example_one_is(tmp_path: Path) -> None:
    """A zero row is the record; a missing row is a scenario the reader does not know exists."""
    import yaml

    rows = st.rows("b6837dd449ca", runs=_tree(tmp_path, []))
    ids = [r.scenario_id for r in rows]

    files = {p.stem: yaml.safe_load(p.read_text()) for p in st.SCENARIOS.glob("*.yaml")}
    assert set(ids) == {k for k, v in files.items() if not v.get("blocked")}
    assert not any(i.startswith("example") for i in ids)
    dev_then_holdout = [r.split for r in rows]
    assert dev_then_holdout == sorted(dev_then_holdout, key=lambda s: s != "dev")
